[package]
name = "zkos-wrapper"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "wrapper"
path = "src/main.rs"

[dependencies]
zkos-wrapper-lib.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

# Needed in main.rs for GPU precomputation loading
boojum = { workspace = true, optional = true }
proof-compression = { workspace = true, optional = true }

[dev-dependencies]
rand.workspace = true
hex = "0.4.3"
libc = "0.2.175"

[features]

default = ["wrap_with_reduced_log_23"]
wrap_final_machine = ["zkos-wrapper-lib/wrap_final_machine"]
wrap_with_reduced_log_23 = ["zkos-wrapper-lib/wrap_with_reduced_log_23"]
gpu = ["zkos-wrapper-lib/gpu", "boojum", "proof-compression"]
