# Used in pull requests

name: Cargo deny check
on: pull_request
permissions: read-all
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clear Cargo Registry
      run: |
        rm -rf ~/.cargo/registry/index
        cargo update
    - uses: EmbarkStudios/cargo-deny-action@v1
