# Used in pull requests

name: Cargo deny check
on: pull_request
permissions: read-all
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: EmbarkStudios/cargo-deny-action@91bf2b620e09e18d6eb78b92e7861937469acedb # v2.0.17
      with:
        command-arguments: "--allow unmaintained --hide-inclusion-graph"
